server:
  port: 8072

eureka:
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 3000
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    register-with-eureka: false